
CREATE TABLESPACE DATA_TBLSPC DATAFILE 
  '/data/MODB/datafile/DATA_TBLSPC_1_01.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED,
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE USER TEST IDENTIFIED BY 123
DEFAULT TABLESPACE DATA_TBLSPC
TEMPORARY TABLESPACE TEMP 
PROFILE DEFAULT 
ACCOUNT UNLOCK;

GRANT CONNECT, RESOURCE TO TEST;
GRANT UNLIMITED TABLESPACE TO TEST;